name: CI Smoke

on:
  push:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -V
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Start API
        run: |
          nohup python -m uvicorn app.main:app --host 127.0.0.1 --port 8000 > uvicorn.log 2>&1 &
          for i in {1..30}; do
            if curl -sSf http://127.0.0.1:8000/healthz > /dev/null; then
              echo "API up"
              exit 0
            fi
            sleep 1
          done
          echo "API failed to start"; cat uvicorn.log; exit 1

      - name: LOINC alias checks
        run: |
          curl -sSf "http://127.0.0.1:8000/lookup?query=ldl"        | jq -r ".results[0].loinc" | grep 2089-1
          curl -sSf "http://127.0.0.1:8000/lookup?query=alk%20phos" | jq -r ".results[0].loinc" | grep 6768-6

      - name: SNOMED check
        run: |
          curl -sSf "http://127.0.0.1:8000/lookup?query=tearing" | jq -r ".results[0].snomed" | grep 231834007

      - name: Dump logs on failure
        if: ${{ failure() }}
        run: |
          echo "==== uvicorn.log ===="
          cat uvicorn.log || true