name: CI Smoke

on:
  push:
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install uvicorn

      - name: Boot API (background)
        run: |
          nohup uvicorn app.main:app --port 8000 &
          sleep 3

      - name: Curl health
        run: |
          curl -sSf http://127.0.0.1:8000/healthz | jq .ok | grep true

      - name: Curl lookup
        run: |
          curl -sSf "http://127.0.0.1:8000/lookup?query=heart%20attack" | jq -r '.results[0].snomed' | grep 22298006
